---
# Application Configuration
app_name: devops-app
docker_image: funnyfoxd/devops-info-service
docker_tag: 2026.02
app_port: 5000
app_internal_port: 5000

# Docker Compose Config
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"

# Container restart policy
restart_policy: unless-stopped

# Environment variables for the app
app_env: {}

# Wipe Logic Control
web_app_wipe: false  # Default: do not wipe
# Set to true to remove application completely
# Wipe only:    ansible-playbook playbooks/deploy.yml -e "web_app_wipe=true" --tags web_app_wipe
# Clean install: ansible-playbook playbooks/deploy.yml -e "web_app_wipe=true"