---
# List of packages to install on all servers
common_packages:
  - python3-pip
  - curl
  - git
  - vim
  - htop
  - ca-certificates
  - gnupg
  - unzip
  - jq

# Timezone (optional)
common_timezone: "Europe/Moscow"

# Default user management settings
common_user_name: "devops"
common_user_groups:
  - "sudo"
