{{- if .Values.hooks.preInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-pre-install" (include "devops-info-service.fullname" .) | quote }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ .Values.hooks.preInstall.weight }}"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "devops-info-service.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-job
          image: {{ .Values.hooks.image }}
          command: ["sh", "-c", {{ .Values.hooks.preInstall.command | quote }}]
{{- end }}
